# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm i
    - run: echo "CI=false" >> $GITHUB_ENV
    - run: npm run build --if-present

    # .env 파일 설정
    - name: Setting .env
      run: |
         echo "REACT_APP_DB_HOST='${{ secrets.REACT_APP_DB_HOST }}'" > .env
         echo "PORT=${{ secrets.PORT }}" >> .env

    # EC2 인스턴스에서 애플리케이션 빌드 및 실행
    - run: |
        npm install
        npm run build
        # React 앱 실행 (예: serve 사용)
        npx serve -s build -l 3000
